- name: Running show commands on Cisco IOS
  hosts: 172.30.254.100
  gather_facts: false
  connection: network_cli
  ansible_network_os: ios

  tasks:
    - name: Run multiple commands on Cisco IOS nodes
      ios_command: #ansible module
        commands: #commands to run
          - show version
          - show ip interface brief

      register: output

    - debug: var=output.stdout_lines
